.catalog:
  name: "Redis"
  version: "v0.0.1"
  description: "Redis"
  uuid: redis-0
  minimum_rancher_version: v0.9.0
  questions:
    - variable: lb_port
      description: "Port to access Redis from external services"
      label: "Redis LB Port"
      required: true
      default: 6379
      type: "int"
      
version: '2'
services:
  redis-lb:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - protocol: tcp
        service: redis
        source_port: ${lb_port}
        target_port: 6379
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  redis:
    scale: 1
    health_check:
      port: 6379
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
