.catalog:
  name: "MongoDB"
  version: "v0.0.1"
  description: "MongoDB"
  uuid: mongodb-0
  minimum_rancher_version: v0.9.0
  questions:
    - variable: lb_port
      description: "Port to access MongoDB from external services"
      label: "MongoDB LB Port"
      required: true
      default: 27017
      type: "int"
      
version: '2'
services:
  mongodb-lb:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - protocol: tcp
        service: mongodb
        source_port: ${lb_port}
        target_port: 27017
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  mongodb:
    scale: 1
    health_check:
      port: 27017
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
